name: wassilni_maak
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  http: ^0.13.4
  font_awesome_flutter: ^10.1.0
  location: ^4.4.0
  dart_code_metrics: ^4.16.0
  webview_flutter: ^3.0.4
  web_scraper: ^0.1.4
  html: ^0.15.0
  flutter_native_splash: ^2.2.4
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  equatable: ^2.0.3
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  google_fonts: ^3.0.1
  firebase_core: ^1.20.0
  js: ^0.6.4
  firebase_remote_config: ^2.0.13
  cloud_firestore: ^3.4.1
  url_launcher: ^6.1.5
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/reversed_taxi_logos.png"

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animation/

  uses-material-design: true
